
import avatar1 from "./../.././assets/images/avatar/1.jpg";
import avatar2 from "./../.././assets/images/avatar/2.jpg";
import avatar3 from "./../.././assets/images/avatar/3.jpg";
import avatar4 from "./../.././assets/images/avatar/4.jpg";
import avatar5 from "./../.././assets/images/avatar/5.jpg";
import avatar6 from "./../.././assets/images/avatar/6.jpg";
import avatar7 from "./../.././assets/images/avatar/7.jpg";
import avatar8 from "./../.././assets/images/avatar/8.jpg";



export const  tradingItem = [
    {
        id:'#1',
        title:'Envato International Meetup 2020',
        number:'454',
        arrow : 'green'
    },
    {
        id:'#2',
        title:'Jakarta Indie Music Festival 2020',
        number:'124',
        arrow : 'red'
    },
    {
        id:'#3',
        title:'Live Choir in Sydney 2020',
        number:'250',
        arrow : 'green'
    },
    {
        id:'#4',
        title:'Artist Performing Festival In Aus..',
        number:'500',
        arrow : 'red'
    },
    {
        id:'#5',
        title:'[LIVE] Football Charity Event 2020',
        number:'426',
        arrow : 'green'
    },
];

export const OrdersList = [
    {
      id: "#0012451",
      date: "04/08/2020 12:34 AM",
      title: "The Story Of Danaou Taba (Musical Drama)",
      customer: "Bella Simatupang",
      location: "London, US",
      quantity: "1 pcs",
      stockLeft: "567k left",
      status: "NO",
      price: "$125.70",
    },
    {
      id: "#0012451",
      date: "04/08/2020 12:34 AM",
      title: "The Story Of Danaou Taba (Musical Drama)",
      customer: "Bella Simatupang",
      location: "Medan, Indonesia",
      quantity: "2 pcs",
      stockLeft: "567k left",
      status: "NO",
      price: "$536.00",
    },
    {
      id: "#0012451",
      date: "04/08/2020 12:34 AM",
      title: "The Story Of Danaou Taba (Musical Drama)",
      customer: "Bella Simatupang",
      location: "Jakarta, Indonesia",
      quantity: "3 pcs",
      stockLeft: "567k left",
      status: "Refund",
      price: "$124.55",
    },
    {
      id: "#0012451",
      date: "04/08/2020 12:34 AM",
      title: "The Story Of Danaou Taba (Musical Drama)",
      customer: "Bella Simatupang",
      location: "Penang, Malaysia",
      quantity: "4 pcs",
      stockLeft: "567k left",
      status: "NO",
      price: "$536.00",
    },
    {
      id: "#0012451",
      date: "04/08/2020 12:34 AM",
      title: "The Story Of Danaou Taba (Musical Drama)",
      customer: "Bella Simatupang",
      location: "Sydney, Australia",
      quantity: "1 pcs",
      stockLeft: "567k left",
      status: "NO",
      price: "$65.22",
    },
    {
      id: "#0012451",
      date: "04/08/2020 12:34 AM",
      title: "The Story Of Danaou Taba (Musical Drama)",
      customer: "Bella Simatupang",
      location: "London, US",
      quantity: "5 pcs",
      stockLeft: "567k left",
      status: "NO",
      price: "$44.00",
    },
    {
      id: "#0012451",
      date: "04/08/2020 12:34 AM",
      title: "The Story Of Danaou Taba (Musical Drama)",
      customer: "Bella Simatupang",
      location: "London, US",
      quantity: "6 pcs",
      stockLeft: "567k left",
      status: "Refund",
      price: "$51.50",
    },
    {
      id: "#0012451",
      date: "04/08/2020 12:34 AM",
      title: "The Story Of Danaou Taba (Musical Drama)",
      customer: "Bella Simatupang",
      location: "Jakarta, Indonesia",
      quantity: "3 pcs",
      stockLeft: "567k left",
      status: "Refund",
      price: "$124.55",
    },
    {
      id: "#0012451",
      date: "04/08/2020 12:34 AM",
      title: "The Story Of Danaou Taba (Musical Drama)",
      customer: "Bella Simatupang",
      location: "Penang, Malaysia",
      quantity: "4 pcs",
      stockLeft: "567k left",
      status: "NO",
      price: "$536.00",
    },
    {
      id: "#0012451",
      date: "04/08/2020 12:34 AM",
      title: "The Story Of Danaou Taba (Musical Drama)",
      customer: "Bella Simatupang",
      location: "Sydney, Australia",
      quantity: "1 pcs",
      stockLeft: "567k left",
      status: "NO",
      price: "$65.22",
    },
    {
        id: "#0012451",
        date: "04/08/2020 12:34 AM",
        title: "The Story Of Danaou Taba (Musical Drama)",
        customer: "Bella Simatupang",
        location: "London, US",
        quantity: "6 pcs",
        stockLeft: "567k left",
        status: "Refund",
        price: "$51.50",
      },
      {
        id: "#0012451",
        date: "04/08/2020 12:34 AM",
        title: "The Story Of Danaou Taba (Musical Drama)",
        customer: "Bella Simatupang",
        location: "Jakarta, Indonesia",
        quantity: "3 pcs",
        stockLeft: "567k left",
        status: "Refund",
        price: "$124.55",
      },
];


export const CustomerTableData = [
    {
        checkboxId: "customCheckBox2",
        id: "#0012451",
        date: "21/11/2017",
        name: "Cive Saluve",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$1,200"
    },
    {
        checkboxId: "customCheckBox3",
        id: "#0012451",
        date: "21/11/2021",
        name: "Bella Simatupang",
        event: "The Powerfull Concert Festival London 2020",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$7,300"
    },
    {
        checkboxId: "customCheckBox4",
        id: "#0012451",
        date: "21/11/2023",
        name: "Andrew Stevano",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$1,500"
    },
    {
        checkboxId: "customCheckBox5",
        id: "#0012451",
        date: "21/11/2023",
        name: "Olivia Brownlee",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$4,500"
    },
    {
        checkboxId: "customCheckBox6",
        id: "#0012451",
        date: "21/11/2017",
        name: "James Roberto",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$1,700"
    },
    {
        checkboxId: "customCheckBox2",
        id: "#0012451",
        date: "21/11/2020",
        name: "Cive Saluve",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$1,200"
    },
    {
        checkboxId: "customCheckBox3",
        id: "#0012451",
        date: "21/11/2023",
        name: "Bella Simatupang",
        event: "The Powerfull Concert Festival London 2020",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$7,300"
    },
    {
        checkboxId: "customCheckBox4",
        id: "#0012451",
        date: "21/11/2020",
        name: "Andrew Stevano",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$1,500"
    },
    {
        checkboxId: "customCheckBox5",
        id: "#0012451",
        date: "21/11/2022",
        name: "Olivia Brownlee",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$4,500"
    },
    {
        checkboxId: "customCheckBox6",
        id: "#0012451",
        date: "21/11/2021",
        name: "James Roberto",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$1,700"
    },
    {
        checkboxId: "customCheckBox4",
        id: "#0012451",
        date: "21/11/2020",
        name: "Andrew Stevano",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$1,500"
    },
    {
        checkboxId: "customCheckBox5",
        id: "#0012451",
        date: "21/11/2020",
        name: "Olivia Brownlee",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$4,500"
    },
    {
        checkboxId: "customCheckBox6",
        id: "#0012451",
        date: "21/11/2020",
        name: "James Roberto",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$1,700"
    },
    {
        checkboxId: "customCheckBox5",
        id: "#0012451",
        date: "21/11/2017",
        name: "Olivia Brownlee",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$4,500"
    },
    {
        checkboxId: "customCheckBox6",
        id: "#0012451",
        date: "21/11/2022",
        name: "James Roberto",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$1,700"
    },
    {
        checkboxId: "customCheckBox4",
        id: "#0012451",
        date: "21/11/2021",
        name: "Andrew Stevano",
        event: "The Story Of Danaou Taba (Musical Drama)",
        location: "Medan Indonesia",
        timestamp: "04/08/2020 12:34 AM",
        price: "$1,500"
    },
    // Add the rest of the rows similarly
];

export const AllReviewsTable = [
    {
      id: "flexCheckDefault1",
      image: avatar1,
      name: "Cindy Hawkins",
      date: "Sunday, 24 July 2024 04:55 PM",
      title: "The Story of Danau Toba (Musical Drama)",
      rating: 4, 
      review: "I've used Ventic for almost ten years. From small general admission church shows to complete turn key ticketing services at Jakarta. I use them for marketing and ticketing on every show. No questions.",
    },
    {
      id: "flexCheckDefault3",
      image: avatar2,
      name: "John Doe",
      date: "Sunday, 24 July 2024 04:55 PM",
      title: "The Story of Danau Toba (Musical Drama)",
      rating: 4,
      review: "Ventic is one of the best vendors we've ever worked with. Thanks for your wonderful, helpful service across the board. It is greatly appreciated!",
    },
    {
      id: "flexCheckDefault4",
      image: avatar3,
      name: "Margaretha Thomp",
      date: "Sunday, 24 July 2024 04:55 PM",
      title: "The Story of Danau Toba (Musical Drama)",
      rating: 4,
      review: "Thank you so much. I love the contact information for marketing purposes especially in case we do this event again in the future. This was my first event running ticketing for STAR, and Ventic was amazing to work with. So helpful, fast to answer any questions, and super easy!",
    },
    {
      id: "flexCheckDefault5",
      image: avatar4,
      name: "Louis Jovanny",
      date: "Sunday, 24 July 2024 04:55 PM",
      title: "The Story of Danau Toba (Musical Drama)",
      rating: 4,
      review: "I've used Ventic for almost ten years. From small general admission church shows to complete turn key ticketing services at Jakarta. I use them for marketing and ticketing on every show. No questions.",
    },
    {
      id: "flexCheckDefault6",
      image: avatar5,
      name: "Cindy Hawkins",
      date: "Sunday, 24 July 2024 04:55 PM",
      title: "The Story of Danau Toba (Musical Drama)",
      rating: 4,
      review: "iTickets has been great from starting up our account to setting up the event. They are always there for questions and have the answers to those questions.",
    },
    {
      id: "flexCheckDefault7",
      image: avatar6,
      name: "Glee Smiley",
      date: "Sunday, 24 July 2024 04:55 PM",
      title: "The Story of Danau Toba (Musical Drama)",
      rating: 4,
      review: "Ventic is one of the best vendors we've ever worked with. Thanks for your wonderful,",
    },
    {
      id: "flexCheckDefault8",
      image: avatar3,
      name: "Margaretha Thomp",
      date: "Sunday, 24 July 2024 04:55 PM",
      title: "The Story of Danau Toba (Musical Drama)",
      rating: 4,
      review: "Thank you so much. I love the contact information for marketing purposes especially in case we do this event again in the future. This was my first event running ticketing for STAR, and Ventic was amazing to work with. So helpful, fast to answer any questions, and super easy!",
    },
    {
      id: "flexCheckDefault9",
      image: avatar4,
      name: "Louis Jovanny",
      date: "Sunday, 24 July 2024 04:55 PM",
      title: "The Story of Danau Toba (Musical Drama)",
      rating: 4,
      review: "I've used Ventic for almost ten years. From small general admission church shows to complete turn key ticketing services at Jakarta. I use them for marketing and ticketing on every show. No questions.",
    },
    {
      id: "flexCheckDefault10",
      image: avatar5,
      name: "Cindy Hawkins",
      date: "Sunday, 24 July 2024 04:55 PM",
      title: "The Story of Danau Toba (Musical Drama)",
      rating: 4,
      review: "iTickets has been great from starting up our account to setting up the event. They are always there for questions and have the answers to those questions.",
    },
];

export const PublicReviewsTable = [
 
  {
    id: "flexCheckDefault5",
    image: avatar4,
    name: "Louis Jovanny",
    date: "Sunday, 24 July 2024 04:55 PM",
    title: "The Story of Danau Toba (Musical Drama)",
    rating: 4,
    review: "I've used Ventic for almost ten years. From small general admission church shows to complete turn key ticketing services at Jakarta. I use them for marketing and ticketing on every show. No questions.",
  },
  {
    id: "flexCheckDefault6",
    image: avatar5,
    name: "Cindy Hawkins",
    date: "Sunday, 24 July 2024 04:55 PM",
    title: "The Story of Danau Toba (Musical Drama)",
    rating: 4,
    review: "iTickets has been great from starting up our account to setting up the event. They are always there for questions and have the answers to those questions.",
  },
  {
    id: "flexCheckDefault7",
    image: avatar6,
    name: "Glee Smiley",
    date: "Sunday, 24 July 2024 04:55 PM",
    title: "The Story of Danau Toba (Musical Drama)",
    rating: 4,
    review: "Ventic is one of the best vendors we've ever worked with. Thanks for your wonderful,",
  },
  {
    id: "flexCheckDefault8",
    image: avatar3,
    name: "Margaretha Thomp",
    date: "Sunday, 24 July 2024 04:55 PM",
    title: "The Story of Danau Toba (Musical Drama)",
    rating: 4,
    review: "Thank you so much. I love the contact information for marketing purposes especially in case we do this event again in the future. This was my first event running ticketing for STAR, and Ventic was amazing to work with. So helpful, fast to answer any questions, and super easy!",
  },
  {
    id: "flexCheckDefault9",
    image: avatar4,
    name: "Louis Jovanny",
    date: "Sunday, 24 July 2024 04:55 PM",
    title: "The Story of Danau Toba (Musical Drama)",
    rating: 4,
    review: "I've used Ventic for almost ten years. From small general admission church shows to complete turn key ticketing services at Jakarta. I use them for marketing and ticketing on every show. No questions.",
  },
  {
    id: "flexCheckDefault10",
    image: avatar5,
    name: "Cindy Hawkins",
    date: "Sunday, 24 July 2024 04:55 PM",
    title: "The Story of Danau Toba (Musical Drama)",
    rating: 4,
    review: "iTickets has been great from starting up our account to setting up the event. They are always there for questions and have the answers to those questions.",
  },
];

export const DeleteReviewsTable = [
  
  {
    id: "flexCheckDefault3",
    image: avatar2,
    name: "John Doe",
    date: "Sunday, 24 July 2024 04:55 PM",
    title: "The Story of Danau Toba (Musical Drama)",
    rating: 4,
    review: "Ventic is one of the best vendors we've ever worked with. Thanks for your wonderful, helpful service across the board. It is greatly appreciated!",
  },
  {
    id: "flexCheckDefault4",
    image: avatar3,
    name: "Margaretha Thomp",
    date: "Sunday, 24 July 2024 04:55 PM",
    title: "The Story of Danau Toba (Musical Drama)",
    rating: 4,
    review: "Thank you so much. I love the contact information for marketing purposes especially in case we do this event again in the future. This was my first event running ticketing for STAR, and Ventic was amazing to work with. So helpful, fast to answer any questions, and super easy!",
  },
  
  {
    id: "flexCheckDefault6",
    image: avatar5,
    name: "Cindy Hawkins",
    date: "Sunday, 24 July 2024 04:55 PM",
    title: "The Story of Danau Toba (Musical Drama)",
    rating: 4,
    review: "iTickets has been great from starting up our account to setting up the event. They are always there for questions and have the answers to those questions.",
  },
  {
    id: "flexCheckDefault7",
    image: avatar6,
    name: "Glee Smiley",
    date: "Sunday, 24 July 2024 04:55 PM",
    title: "The Story of Danau Toba (Musical Drama)",
    rating: 4,
    review: "Ventic is one of the best vendors we've ever worked with. Thanks for your wonderful,",
  },
  {
    id: "flexCheckDefault8",
    image: avatar3,
    name: "Margaretha Thomp",
    date: "Sunday, 24 July 2024 04:55 PM",
    title: "The Story of Danau Toba (Musical Drama)",
    rating: 4,
    review: "Thank you so much. I love the contact information for marketing purposes especially in case we do this event again in the future. This was my first event running ticketing for STAR, and Ventic was amazing to work with. So helpful, fast to answer any questions, and super easy!",
  },
  {
    id: "flexCheckDefault9",
    image: avatar4,
    name: "Louis Jovanny",
    date: "Sunday, 24 July 2024 04:55 PM",
    title: "The Story of Danau Toba (Musical Drama)",
    rating: 4,
    review: "I've used Ventic for almost ten years. From small general admission church shows to complete turn key ticketing services at Jakarta. I use them for marketing and ticketing on every show. No questions.",
  },
  
];

export const FlatIconData = [
  { title:'flaticon-381-add',svgtype:'flaticon-381-add',},
  { title:'flaticon-381-add-1',svgtype:'flaticon-381-add-1',},
  { title:'flaticon-381-add-2',svgtype:'flaticon-381-add-2',},
  { title:'flaticon-381-add-3',svgtype:'flaticon-381-add-3',},
  { title:'flaticon-381-alarm-clock',svgtype:'flaticon-381-alarm-clock',},
  { title:'flaticon-381-alarm-clock-1',svgtype:'flaticon-381-alarm-clock-1',},
  { title:'flaticon-381-album',svgtype:'flaticon-381-album',},
  { title:'flaticon-381-album-1',svgtype:'flaticon-381-album-1',},
  { title:'flaticon-381-album-2',svgtype:'flaticon-381-album-2',},
  { title:'flaticon-381-album-3',svgtype:'flaticon-381-album-3',},
  { title:'flaticon-381-app',svgtype:'flaticon-381-app',},
  { title:'flaticon-381-archive',svgtype:'flaticon-381-archive',},
  { title:'flaticon-381-back',svgtype:'flaticon-381-back',},
  { title:'flaticon-381-back-1',svgtype:'flaticon-381-back-1',},
  { title:'flaticon-381-back-2',svgtype:'flaticon-381-back-2',},
  { title:'flaticon-381-background',svgtype:'flaticon-381-background',},
  { title:'flaticon-381-background-1',svgtype:'flaticon-381-background-1',},
  { title:'flaticon-381-battery',svgtype:'flaticon-381-battery',},
  { title:'flaticon-381-battery-1',svgtype:'flaticon-381-battery-1',},
  { title:'flaticon-381-battery-2',svgtype:'flaticon-381-battery-2',},
  { title:'flaticon-381-battery-3',svgtype:'flaticon-381-battery-3',},
  { title:'flaticon-381-battery-4',svgtype:'flaticon-381-battery-4',},
  { title:'flaticon-381-battery-5',svgtype:'flaticon-381-battery-5',},
  { title:'flaticon-381-battery-6',svgtype:'flaticon-381-battery-6',},
  { title:'flaticon-381-battery-7',svgtype:'flaticon-381-battery-7',},
  { title:'flaticon-381-battery-8',svgtype:'flaticon-381-battery-8',},
  { title:'flaticon-381-battery-9',svgtype:'flaticon-381-battery-9',},
  { title:'flaticon-381-binoculars',svgtype:'flaticon-381-binoculars',},
  { title:'flaticon-381-blueprint',svgtype:'flaticon-381-blueprint',},
  { title:'flaticon-381-bluetooth',svgtype:'flaticon-381-bluetooth',},
  { title:'flaticon-381-bluetooth-1',svgtype:'flaticon-381-bluetooth-1',},
  { title:'flaticon-381-book',svgtype:'flaticon-381-book',},
  { title:'flaticon-381-bookmark',svgtype:'flaticon-381-bookmark',},
  { title:'flaticon-381-bookmark-1',svgtype:'flaticon-381-bookmark-1',},
  { title:'flaticon-381-box',svgtype:'flaticon-381-box',},
  { title:'flaticon-381-box-1',svgtype:'flaticon-381-box-1',},
  { title:'flaticon-381-box-2',svgtype:'flaticon-381-box-2',},
  { title:'flaticon-381-briefcase',svgtype:'flaticon-381-briefcase',},
  { title:'flaticon-381-broken-heart',svgtype:'flaticon-381-broken-heart',},
  { title:'flaticon-381-broken-link',svgtype:'flaticon-381-broken-link',},
  { title:'flaticon-381-calculator',svgtype:'flaticon-381-calculator',},
  { title:'flaticon-381-calculator-1',svgtype:'flaticon-381-calculator-1',},
  { title:'flaticon-381-calendar',svgtype:'flaticon-381-calendar',},
  { title:'flaticon-381-calendar-1',svgtype:'flaticon-381-calendar-1',},
  { title:'flaticon-381-calendar-2',svgtype:'flaticon-381-calendar-2',},
  { title:'flaticon-381-calendar-3',svgtype:'flaticon-381-calendar-3',},
  { title:'flaticon-381-calendar-4',svgtype:'flaticon-381-calendar-4',},
  { title:'flaticon-381-calendar-5',svgtype:'flaticon-381-calendar-5',},
  { title:'flaticon-381-calendar-6',svgtype:'flaticon-381-calendar-6',},
  { title:'flaticon-381-calendar-7',svgtype:'flaticon-381-calendar-7',},
  { title:'flaticon-381-clock',svgtype:'flaticon-381-clock',},
  { title:'flaticon-381-clock-1',svgtype:'flaticon-381-clock-1',},
  { title:'flaticon-381-clock-2',svgtype:'flaticon-381-clock-2',},
  { title:'flaticon-381-close',svgtype:'flaticon-381-close',},
  { title:'flaticon-381-cloud',svgtype:'flaticon-381-cloud',},
  { title:'flaticon-381-cloud-computing',svgtype:'flaticon-381-cloud-computing',},
  { title:'flaticon-381-command',svgtype:'flaticon-381-command',},
  { title:'flaticon-381-compact-disc',svgtype:'flaticon-381-compact-disc',},
  { title:'flaticon-381-compact-disc-1',svgtype:'flaticon-381-compact-disc-1',},
  { title:'flaticon-381-compact-disc-2',svgtype:'flaticon-381-compact-disc-2',},
  { title:'flaticon-381-compass',svgtype:'flaticon-381-compass',},
  { title:'flaticon-381-compass-1',svgtype:'flaticon-381-compass-1',},
  { title:'flaticon-381-compass-2',svgtype:'flaticon-381-compass-2',},
  { title:'flaticon-381-controls',svgtype:'flaticon-381-controls',},
  { title:'flaticon-381-controls-1',svgtype:'flaticon-381-controls-1',},
  { title:'flaticon-381-controls-2',svgtype:'flaticon-381-controls-2',},
  { title:'flaticon-381-controls-3',svgtype:'flaticon-381-controls-3',},
  { title:'flaticon-381-controls-4',svgtype:'flaticon-381-controls-4',},
  { title:'flaticon-381-switch-4',svgtype:'flaticon-381-switch-4',},
  { title:'flaticon-381-controls-5',svgtype:'flaticon-381-controls-5',},
  { title:'flaticon-381-controls-6',svgtype:'flaticon-381-controls-6',},
  { title:'flaticon-381-database',svgtype:'flaticon-381-database',},
  { title:'flaticon-381-database-1',svgtype:'flaticon-381-database-1',},
  { title:'flaticon-381-diamond',svgtype:'flaticon-381-diamond',},
  { title:'flaticon-381-diploma',svgtype:'flaticon-381-diploma',},
  { title:'flaticon-381-dislike',svgtype:'flaticon-381-dislike',},
  { title:'flaticon-381-divide',svgtype:'flaticon-381-divide',},
  { title:'flaticon-381-earth-globe',svgtype:'flaticon-381-earth-globe',},
];

export const AllTicketData = [
  {
    checkboxId: "customCheckBox4",
    role: "Accountant",
    location: "Tokyo",
    age: 63,
    description: "perferendis",
    startDate: "2011/07/25",
    status: "Re-Open",
    badgeColor: 'badge-secondary',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox5",
    role: "Junior Technical Author",
    location: "San Francisco",
    age: 66,
    description: "commodi",
    startDate: "2009/01/12",
    status: "New",
    badgeColor : 'badge-danger',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox6",
    role: "Senior Javascript Developer",
    location: "Edinburgh",
    age: 22,
    description: "perferendis",
    startDate: "2012/03/29",
    status: "Inprogress",
    badgeColor : 'badge-info',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox7",
    role: "Accountant",
    location: "Tokyo",
    age: 33,
    description: "repudiandae",
    startDate: "2008/11/28",
    status: "New",
    badgeColor : 'badge-danger',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox8",
    role: "Integration Specialist",
    location: "New York",
    age: 61,
    description: "commodi",
    startDate: "2012/12/02",
    status: "On-Hold",
    badgeColor:'badge-warning',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox9",
    role: "Sales Assistant",
    location: "San Francisco",
    age: 59,
    description: "repudiandae",
    startDate: "2012/08/06",
    status: "Inprogress",
    badgeColor : 'badge-info',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox10",
    role: "Integration Specialist",
    location: "Tokyo",
    age: 55,
    description: "molestiae",
    startDate: "2010/10/14",
    status: "Re-Open",
    badgeColor: 'badge-secondary',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox11",
    role: "Javascript Developer",
    location: "San Francisco",
    age: 39,
    description: "repudiandae",
    startDate: "2009/09/15",
    status: "New",
    badgeColor : 'badge-danger',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox12",
    role: "Software Engineer",
    location: "Edinburgh",
    age: 23,
    description: "molestiae",
    startDate: "2008/12/13",
    status: "Inprogress",
    badgeColor : 'badge-info',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox13",
    role: "System Architect",
    location: "Edinburgh",
    age: 61,
    description: "molestiae",
    startDate: "2011/04/25",
    status: "Inprogress",
    badgeColor : 'badge-info',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox5",
    role: "Junior Technical Author",
    location: "San Francisco",
    age: 66,
    description: "commodi",
    startDate: "2009/01/12",
    status: "New",
    badgeColor : 'badge-danger',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox6",
    role: "Senior Javascript Developer",
    location: "Edinburgh",
    age: 22,
    description: "perferendis",
    startDate: "2012/03/29",
    status: "Inprogress",
    badgeColor : 'badge-info',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox7",
    role: "Accountant",
    location: "Tokyo",
    age: 33,
    description: "repudiandae",
    startDate: "2008/11/28",
    status: "New",
    badgeColor : 'badge-danger',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox8",
    role: "Integration Specialist",
    location: "New York",
    age: 61,
    description: "commodi",
    startDate: "2012/12/02",
    status: "On-Hold",
    badgeColor:'badge-warning',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox9",
    role: "Sales Assistant",
    location: "San Francisco",
    age: 59,
    description: "repudiandae",
    startDate: "2012/08/06",
    status: "Inprogress",
    badgeColor : 'badge-info',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
  {
    checkboxId: "customCheckBox10",
    role: "Integration Specialist",
    location: "Tokyo",
    age: 55,
    description: "molestiae",
    startDate: "2010/10/14",
    status: "Re-Open",
    badgeColor: 'badge-secondary',
    action: "Assign",
    timeElapsed: "9 years ago",
    options: ["Edit", "Delete"]
  },
];

export const ChatImageData = [
  { image : avatar1,},
  { image : avatar2,},
  { image : avatar3,},
  { image : avatar4,},
  { image : avatar5,},
  { image : avatar6,},
];

export const chatDataList = [
  {
    id: 1,    
    chatImg: avatar4,
    name: "Product Team",
    message: "Lorem ipsum dolor sit amet.",
    time: "12:45 PM",
  },
  {   
    id: 2,
    chatImg: avatar3,
    name: "Tony Soap",
    message: "Lorem ipsum dolor sit amet is the dummy text.",
    time: "12:45 PM",
  },
  {   
    id: 3,
    chatImg: avatar2,
    name: "Karen Hope",
    message: "Lorem ipsum dolor sit amet is the dummy text.",
    time: "12:45 PM",
  },
];
export const chatDataList2 = [
  {
    chatBxClass: "chat-bx",
    chatImg: avatar1,
    name: "Design Team (32)",
    message: "Lorem ipsum dolor sit amet.",
    time: "12:45 PM",
  },
  {
    chatBxClass: "chat-bx",
    chatImg: avatar8,
    name: "Tony Soap",
    message: "Lorem ipsum dolor sit amet is the dummy text.",
    time: "12:45 PM",
  },
  {
    chatBxClass: "chat-bx active",
    chatImg: avatar7,
    name: "Karen Hope",
    message: "Lorem ipsum dolor sit amet is the dummy text.",
    time: "12:45 PM",
  },
];

export const SolidColorOption = [
  { tilte: 'bg-primary', chossecolor: 'bg-primary text-white' },
  { tilte: 'bg-primary-subtle', chossecolor: 'bg-primary-subtle text-primary-emphasis' },
  { tilte: 'bg-secondary', chossecolor: ' bg-secondary text-white' },
  { tilte: 'bg-secondary-subtle', chossecolor: 'bg-secondary-subtle text-secondary-emphasis' },
  { tilte: 'bg-success', chossecolor: 'bg-success text-white' },
  { tilte: 'bg-success-subtle', chossecolor: 'bg-success-subtle text-success-emphasis' },
  { tilte: 'bg-danger', chossecolor: 'bg-danger text-white' },
  { tilte: 'bg-danger-subtle', chossecolor: 'bg-danger-subtle text-danger-emphasis' },
  { tilte: 'bg-warning', chossecolor: 'bg-warning text-dark' },
  { tilte: 'bg-warning-subtle', chossecolor: 'bg-warning-subtle text-warning-emphasis' },
  { tilte: 'bg-info', chossecolor: 'bg-info text-dark' },
  { tilte: 'bg-info-subtle', chossecolor: 'bg-info-subtle text-info-emphasis' },
  { tilte: 'bg-light', chossecolor: 'bg-light text-dark' },
  { tilte: 'bg-light-subtle', chossecolor: 'bg-light-subtle text-light-emphasis' },
  { tilte: 'bg-dark', chossecolor: 'bg-dark text-white' },
  { tilte: 'bg-dark-subtle', chossecolor: 'bg-dark-subtle text-dark-emphasis' },
  { tilte: 'bg-body-secondary', chossecolor: 'bg-body-secondary' },
  { tilte: 'bg-body-tertiary', chossecolor: 'bg-body-tertiary' },
  { tilte: 'bg-body', chossecolor: 'bg-body text-body' },
  { tilte: 'bg-black', chossecolor: 'bg-black text-white' },
  { tilte: 'bg-white', chossecolor: 'bg-white text-dark' },
  { tilte: 'bg-transparent', chossecolor: 'bg-transparent text-body' },
];

export const OtherColor = [
  {
      coloum: 'col-xl-3 col-sm-6',
      innerContent: [
          { colorStyle1: 'blue-100' },
          { colorStyle1: 'blue-200' },
          { colorStyle1: 'blue-300' },
          { colorStyle1: 'blue-400' },
          { colorStyle1: 'blue-500' },
          { colorStyle1: 'blue-600' },
          { colorStyle1: 'blue-700' },
          { colorStyle1: 'blue-800' },
          { colorStyle1: 'blue-900' },
      ],
  },
  {
      coloum: 'col-xl-3 col-sm-6',
      innerContent: [
          { colorStyle1: 'indigo-100' },
          { colorStyle1: 'indigo-200' },
          { colorStyle1: 'indigo-300' },
          { colorStyle1: 'indigo-400' },
          { colorStyle1: 'indigo-500' },
          { colorStyle1: 'indigo-600' },
          { colorStyle1: 'indigo-700' },
          { colorStyle1: 'indigo-800' },
          { colorStyle1: 'indigo-900' },
      ],
  },
  {
      coloum: 'col-xl-3 col-sm-6',
      innerContent: [
          { colorStyle1: 'purple-100' },
          { colorStyle1: 'purple-200' },
          { colorStyle1: 'purple-300' },
          { colorStyle1: 'purple-400' },
          { colorStyle1: 'purple-500' },
          { colorStyle1: 'purple-600' },
          { colorStyle1: 'purple-700' },
          { colorStyle1: 'purple-800' },
          { colorStyle1: 'purple-900' },
      ],
  },
  {
      coloum: 'col-xl-3 col-sm-6',
      innerContent: [
          { colorStyle1: 'pink-100' },
          { colorStyle1: 'pink-200' },
          { colorStyle1: 'pink-300' },
          { colorStyle1: 'pink-400' },
          { colorStyle1: 'pink-500' },
          { colorStyle1: 'pink-600' },
          { colorStyle1: 'pink-700' },
          { colorStyle1: 'pink-800' },
          { colorStyle1: 'pink-900' },
      ],
  },
  {
      coloum: 'col-xl-3 col-sm-6',
      innerContent: [
          { colorStyle1: 'red-100' },
          { colorStyle1: 'red-200' },
          { colorStyle1: 'red-300' },
          { colorStyle1: 'red-400' },
          { colorStyle1: 'red-500' },
          { colorStyle1: 'red-600' },
          { colorStyle1: 'red-700' },
          { colorStyle1: 'red-800' },
          { colorStyle1: 'red-900' },
      ],
  },
  {
      coloum: 'col-xl-3 col-sm-6',
      innerContent: [
          { colorStyle1: 'orange-100' },
          { colorStyle1: 'orange-200' },
          { colorStyle1: 'orange-300' },
          { colorStyle1: 'orange-400' },
          { colorStyle1: 'orange-500' },
          { colorStyle1: 'orange-600' },
          { colorStyle1: 'orange-700' },
          { colorStyle1: 'orange-800' },
          { colorStyle1: 'orange-900' },
      ],
  },
  {
      coloum: 'col-xl-3 col-sm-6',
      innerContent: [
          { colorStyle1: 'yellow-100' },
          { colorStyle1: 'yellow-200' },
          { colorStyle1: 'yellow-300' },
          { colorStyle1: 'yellow-400' },
          { colorStyle1: 'yellow-500' },
          { colorStyle1: 'yellow-600' },
          { colorStyle1: 'yellow-700' },
          { colorStyle1: 'yellow-800' },
          { colorStyle1: 'yellow-900' },
      ],
  },
  {
      coloum: 'col-xl-3 col-sm-6',
      innerContent: [
          { colorStyle1: 'green-100' },
          { colorStyle1: 'green-200' },
          { colorStyle1: 'green-300' },
          { colorStyle1: 'green-400' },
          { colorStyle1: 'green-500' },
          { colorStyle1: 'green-600' },
          { colorStyle1: 'green-700' },
          { colorStyle1: 'green-800' },
          { colorStyle1: 'green-900' },
      ],
  },
  {
      coloum: 'col-xl-3 col-sm-6',
      innerContent: [
          { colorStyle1: 'teal-100' },
          { colorStyle1: 'teal-200' },
          { colorStyle1: 'teal-300' },
          { colorStyle1: 'teal-400' },
          { colorStyle1: 'teal-500' },
          { colorStyle1: 'teal-600' },
          { colorStyle1: 'teal-700' },
          { colorStyle1: 'teal-800' },
          { colorStyle1: 'teal-900' },
      ],
  },
  {
      coloum: 'col-xl-3 col-sm-6',
      innerContent: [
          { colorStyle1: 'cyan-100' },
          { colorStyle1: 'cyan-200' },
          { colorStyle1: 'cyan-300' },
          { colorStyle1: 'cyan-400' },
          { colorStyle1: 'cyan-500' },
          { colorStyle1: 'cyan-600' },
          { colorStyle1: 'cyan-700' },
          { colorStyle1: 'cyan-800' },
          { colorStyle1: 'cyan-900' },
      ],
  },
  {
      coloum: 'col-xl-3 col-sm-6',
      innerContent: [
          { colorStyle1: 'gray-100' },
          { colorStyle1: 'gray-200' },
          { colorStyle1: 'gray-300' },
          { colorStyle1: 'gray-400' },
          { colorStyle1: 'gray-500' },
          { colorStyle1: 'gray-600' },
          { colorStyle1: 'gray-700' },
          { colorStyle1: 'gray-800' },
          { colorStyle1: 'gray-900' },
      ],
  },

];

export const AllCustomer = [
  {
    name : 'Glee Smiley',
    gender: 'Male',
    usertype:'Customer',
    regdate:'15 Mar,2020',
    expiredate : '15 Mar,2026',
    statuscolor:'success',
    status: 'active'
  },
  {
    name : 'Louis Jovanny',
    gender: 'Male',
    usertype:'Guest',
    regdate:'21 May,2017',
    expiredate : '30 July,2027',
    statuscolor:'danger',
    status: 'Inactive'  
  },
  {
    name : 'Cindy Hawkins',
    gender: 'Male',
    usertype:'Guest',
    regdate:'15 Apr,2020',
    expiredate : '18 Feb,2026',
    statuscolor:'success',
    status: 'active'
  },
  {
    name : 'Glee Smiley',
    gender: 'Female',
    usertype:'Customer',
    regdate:'11 May,2018',
    expiredate : '10 Dec,2027',
    statuscolor:'danger',
    status: 'Inactive'  
  },
  {
    name : 'Timothy L. Brodbeck',
    gender: 'Male',
    usertype:'Customer',
    regdate:'25 Mar,2020',
    expiredate : '29 July,2027',
    statuscolor:'success',
    status: 'active'
  },
  {
    name : 'Louis Jovanny',
    gender: 'Male',
    usertype:'Guest',
    regdate:'20 Mar,2019',
    expiredate : '30 Mar,2027',
    statuscolor:'danger',
    status: 'Inactive'  
  },
  {
    name : 'Cindy Hawkins',
    gender: 'Male',
    usertype:'Guest',
    regdate:'21 Apr,2016',
    expiredate : '20 June,2029',
    statuscolor:'success',
    status: 'active'
  },
  {
    name : 'Glee Smiley',
    gender: 'Female',
    usertype:'Customer',
    regdate:'16 Dec,2017',
    expiredate : '14 Nov,2025',
    statuscolor:'danger',
    status: 'Inactive'  
  },
    
]; 